export const PRIVACY_CONSTANTS = {
  lastUpdated: 'August 16, 2026',
  websiteUrl: 'https://jobmouka.com/',
  contactEmail: 'renukadevi@jobmouka.com',

  company: {
    name: 'SanChaM Technology Solutions Private Limited',
    address: '#3274/7-d-1 Ward No 23, Karikatti Road, Saundatti, Belgaum, Saundatti, Karnataka, India, 591126',
    appName: 'JobMouka',
    country: 'Karnataka, India',
  },

  definitions: [
    { term: 'Account', def: 'A unique account created for You to access Our Service or parts of Our Service.' },
    { term: 'Affiliate', def: 'An entity that controls, is controlled by, or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.' },
    { term: 'Application', def: 'Refers to JobMouka, the software program provided by the Company.' },
    { term: 'Company', def: 'Refers to SanChaM Technology Solutions Private Limited, #3274/7-d-1 Ward No 23, Karikatti Road, Saundatti, Belgaum, Saundatti, Karnataka, India, 591126.' },
    { term: 'Cookies', def: 'Small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website, among its many uses.' },
    { term: 'Country/State', def: 'Karnataka, India.' },
    { term: 'Device', def: 'Any device that can access the Service, such as a computer, a cell phone or a digital tablet.' },
    { term: 'Personal Data', def: 'Any information that relates to an identified or identifiable individual. We use "Personal Data" and "Personal Information" interchangeably unless a law uses a specific term.' },
    { term: 'Service', def: 'Refers to the Application or the Website or both.' },
    { term: 'Service Provider', def: 'Any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.' },
    { term: 'Usage Data', def: 'Data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).' },
    { term: 'User', def: 'Any individual who accesses or uses the Service.' },
    { term: 'Website', def: 'Refers to https://jobmouka.com/, accessible from https://jobmouka.com/.' },
    { term: 'You', def: 'The individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.' },
  ],

  personalDataTypes: [
    'Email address',
    'First name and last name',
    'Phone number',
    'Address, State, Province, ZIP/Postal code, City',
  ],

  cookieTypes: [
    {
      name: 'Necessary / Essential Cookies',
      type: 'Session Cookies',
      administeredBy: 'Us',
      purpose: 'These Cookies are essential to provide You with services available through the Website and to enable You to use some of its features. They help to authenticate users and prevent fraudulent use of user accounts. Without these Cookies, the services that You have asked for cannot be provided, and We only use these Cookies to provide You with those services.',
    },
    {
      name: 'Cookies Policy / Notice Acceptance Cookies',
      type: 'Persistent Cookies',
      administeredBy: 'Us',
      purpose: 'These Cookies identify whether users have accepted the use of cookies on the Website and record the consent choices You have made, so that We can honor those choices on future visits.',
    },
    {
      name: 'Functionality Cookies',
      type: 'Persistent Cookies',
      administeredBy: 'Us',
      purpose: 'These Cookies allow Us to remember choices You make when You use the Website, such as remembering Your Account login details or language preference. The purpose of these Cookies is to provide You with a more personal experience and to avoid You having to re-enter Your preferences every time You use the Website.',
    },
  ],

  dataUsagePurposes: [
    'To provide and maintain Our Service, including to monitor the usage of Our Service.',
    'To manage Your Account: to manage Your registration as a user of the Service. The Personal Data You provide can give You access to different functionalities of the Service that are available to You as a registered user.',
    'For the performance of a contract: the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased or of any other contract with Us through the Service.',
    'To contact You: To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a mobile application\'s push notifications regarding updates or informative communications related to the functionalities, products or contracted services, including the security updates, when necessary or reasonable for their implementation.',
    'To provide You with news, special offers, and general information about other goods, services and events which We offer that are similar to those that You have already purchased or inquired about.',
    'To manage Your requests: To attend and manage Your requests to Us.',
    'For business transfers: We may use Your Personal Data to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our assets.',
    'For other purposes: We may use Your information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of Our promotional campaigns, and evaluating and improving Our Service, products, services, marketing and Your experience.',
  ],

  dataSharingSituations: [
    { label: 'With Service Providers', detail: 'We may share Your Personal Data with Service Providers to monitor and analyze the use of Our Service, and to contact You.' },
    { label: 'For business transfers', detail: 'We may share or transfer Your Personal Data in connection with, or during negotiations of, any merger, sale of Company assets, financing, or acquisition of all or a portion of Our business to another company.' },
    { label: 'With Affiliates', detail: 'We may share Your Personal Data with Our affiliates, in which case We will require those affiliates to honor this Privacy Policy.' },
    { label: 'With other users', detail: 'If Our Service offers public areas, when You share Personal Data or otherwise interact in the public areas with other users, such information may be viewed by all users and may be publicly distributed outside the Service.' },
    { label: 'With Your consent', detail: 'We may disclose Your Personal Data for any other purpose with Your consent.' },
  ],

  smsConsentTypes: [
    'Customer care and support',
    'Account notifications, such as activity, status, or renewal reminders',
    'Delivery notifications and updates on the status of a delivery',
    'Authentication messages, such as one-time passwords (OTP) and passcodes',
    'Security alerts, such as suspicious login attempts or unusual account activity',
    'Marketing and promotional offers, discounts, and other promotional content',
  ],

  retentionPeriods: [
    { category: 'Account Information', detail: 'User Accounts: retained for the duration of Your Account relationship plus up to 24 months after account closure.' },
    { category: 'Customer Support Data', detail: 'Support tickets and correspondence: up to 24 months from the date of ticket closure. Chat transcripts: up to 24 months for quality assurance.' },
    { category: 'Usage Data', detail: 'Website analytics data: up to 24 months. Application usage statistics: up to 24 months. Server logs: up to 24 months for security monitoring.' },
  ],

  minAge: 16,
};
